/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.server.controller;

import com.example.server.model.Pet;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@RestController
public class PetApiController {

    @RequestMapping(
        method = RequestMethod.POST,
        value = "/pet/createPet",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    public ResponseEntity<Pet> createNewPet(@RequestBody Pet pet) {
        return ResponseEntity.ok(pet);
    }

    @RequestMapping(
        method = RequestMethod.GET,
        value = "/pet/{id}",
        produces = { "application/json", "application/xml" }
    )
    public ResponseEntity<Pet> findById(@PathVariable("id") Integer id) {
        Pet pet = new Pet(1, "cat");
        return ResponseEntity.ok(pet);
    }

    @RequestMapping(
        method = RequestMethod.GET,
        value = "/pet/",
        produces = { "application/json" }
    )
    public ResponseEntity<List<Pet>> getAllPet() {
        List<Pet> listPet = new ArrayList<>();
        listPet.add(new Pet(1, "cat"));
        listPet.add(new Pet(1, "dog"));
        return ResponseEntity.ok(listPet);
    }

    @RequestMapping(
            method = RequestMethod.POST,
            value = "/pet/create",
            produces = { "application/json" }
    )
    public void createPet(@RequestBody List<Pet> listPet) {

    }

    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/pet/update",
            produces = { "application/json" }
    )
    public void updatePet(@RequestBody Pet pet) {

    }

}
