/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.server.controller;

import com.example.server.domain.Pet;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@Slf4j
@RestController
@RequestMapping("/pet")
@RequiredArgsConstructor
public class PetApiController {

    @RequestMapping(
        method = RequestMethod.GET,
        value = "/{id}",
        produces = { "application/json", "application/xml" }
    )
    public ResponseEntity<Pet> findById(@PathVariable("id") Integer id) throws InterruptedException {

        Thread.sleep(10000);
        Pet pet = new Pet(1, "cat");

        // can push data to Kafka of message queue and code API of client to notify
        // and client will read data from Kafka of message queue
        return ResponseEntity.ok(pet);
    }

    @RequestMapping(
        method = RequestMethod.GET,
        value = "",
        produces = { "application/json" }
    )
    public ResponseEntity<List<Pet>> getAllPet( @RequestHeader HttpHeaders headers) throws InterruptedException {
        Thread.sleep(10000);
        List<Pet> listPet = new ArrayList<>();
        listPet.add(new Pet(1, "cat"));
        listPet.add(new Pet(2, "dog"));
        System.out.println(headers.get("requestId"));
        return ResponseEntity.ok(listPet);
    }

    @RequestMapping(
            method = RequestMethod.POST,
            value = "/create",
            produces = { "application/json" }
    )
    public void createPet(@RequestBody List<Pet> listPet) {

    }

    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/update",
            produces = { "application/json" }
    )
    public void updatePet(@RequestBody Pet pet) {

    }

}
